version: '3.9'
services:
  rails:
    build: .
    ports:
      - "${RAILS_PORT}:3000"
    depends_on:
      - "redis"
    restart: unless-stopped
  redis:
    image: redis
    restart: unless-stopped
